name: Docker Image CI

on:
  push:
    branches: ["js-tmp"]
jobs:
  build_and_push:
    runs-on: ubuntu-latest
    environment: production

    steps:
      - uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build . --file Dockerfile --tag ${{ github.actor }}/octopus-usage-exporter:latest

      - name: Login to GitHub Container Registry
        uses: docker/login-action@v1
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Tag Docker image for GitHub Container Registry
        run: docker tag ${{ github.actor }}/octopus-usage-exporter:latest ghcr.io/${{ github.actor }}/octopus-usage-exporter:latest

      - name: Push Docker image to GitHub Container Registry
        run: docker push ghcr.io/${{ github.actor }}/octopus-usage-exporter:latest
